# https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/?envType=study-plan-v2&envId=top-interview-150
def sorted_array_to_bst(self, nums: List[int]) -> Optional[TreeNode]:
    ...
